export const ERROR = 'ERROR'

export const CHANGE_P1_SCORE_15 = 'CHANGE_P1_SCORE_15';
export const CHANGE_P1_SCORE_16 = 'CHANGE_P1_SCORE_16';
export const CHANGE_P1_SCORE_17 = 'CHANGE_P1_SCORE_17';
export const CHANGE_P1_SCORE_18 = 'CHANGE_P1_SCORE_18';
export const CHANGE_P1_SCORE_19 = 'CHANGE_P1_SCORE_19';
export const CHANGE_P1_SCORE_20 = 'CHANGE_P1_SCORE_20';
export const CHANGE_P1_SCORE_50 = 'CHANGE_P1_SCORE_50';

export const CHANGE_P2_SCORE_15 = 'CHANGE_P2_SCORE_15';
export const CHANGE_P2_SCORE_16 = 'CHANGE_P2_SCORE_16';
export const CHANGE_P2_SCORE_17 = 'CHANGE_P2_SCORE_17';
export const CHANGE_P2_SCORE_18 = 'CHANGE_P2_SCORE_18';
export const CHANGE_P2_SCORE_19 = 'CHANGE_P2_SCORE_19';
export const CHANGE_P2_SCORE_20 = 'CHANGE_P2_SCORE_20';
export const CHANGE_P2_SCORE_50 = 'CHANGE_P2_SCORE_50';

export const CHANGE_P1_NAME = 'CHANGE_P1_NAME';
export const CHANGE_P2_NAME = 'CHANGE_P2_NAME';
